name: expense_tracker
description: A Flutter expense tracking application

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=2.17.0 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  animations: ^2.0.7
  font_awesome_flutter: ^10.7.0
  lottie: ^2.5.0
  video_player: ^2.8.2   # مهم جداً للفيديو

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/google_icon.png
    - assets/images/bar_chart_1.png
    - assets/images/transparent-coffee-cup-black-and-white-mug-with-coffee-beans6614631a4bc771.32287189.webp
    - assets/videos/xJ9B487B59DKI59kOb.mp4   # <-- الفيديو هنا
